#!/bin/dash

# TODO
# catch err: 
    # usage: legit-commit [-a] -m commit-message
        
if [ $# -ne 2 ] || [ $1 != "-m" ] || echo "$2" | egrep -q "^-|^$"; then
    echo "usage: legit-commit [-a] -m commit-message"; exit 0;  
fi

index='.legit/index';
if [ -f "$index/.index" ]; then
    commit_flag="0";
    for i in `ls $index`
    do  
        hash="`sha1sum $i | cut -d' ' -f1`";
        
        if [ "`grep $hash "$index/.index"`" ]; then
            # echo "$hash";
            continue;
        else
            commit_flag="1";
        fi
    done
else
    commit_flag="1";
    touch "$index/.index";
fi

# echo "$commit_flag";
if [ "$commit_flag" -eq 0 ]; then
    echo "nothing to commit";
    exit 0;
fi

# store latest commit
commit_num="0";
msg_file='.legit/COMMIT_EDITMSG';
if [ -s $msg_file ]; then            # Not Empty
     # Format: # msg
     commit_num=`cut -d' ' -f1 $msg_file`;
     commit_num=`expr $commit_num + 1`
fi
echo "$commit_num $2" > $msg_file;

>"$index/.index"
# moving from index to repo
repo='.legit/logs/repo';
# ls $index;    # DEBUG
snapshot="$repo/.snapshot.$commit_num";
mkdir $snapshot;

for i in `ls $index`
do
    cp "$index/$i" "$snapshot/$i";
    # rm "$index/$i";
    echo "`sha1sum $snapshot/$i`" >> "$index/.index";       # update hashes
done

# legit logs
log='.legit/logs/HEAD';
# log_hash=`sha1sum $snapshot`;
# echo 
log_commit="commit: $commit_num $2";
log_info="$log_commit";
echo "$log_info" >> $log;

echo "Committed as commit $commit_num";
