#!/bin/dash

# TODO
# catch err:
    # usage: legit-commit [-a] -m commit-message

if [ ! -d '.legit' ]; then
    echo "legit-commit: error: no .legit directory containing legit repository exists";
    exit 1;
fi

all="0";
msg="0";
valid_msg="0";
for i in "$@"
do
    # echo "$i";
    if [ "$i" =  "-a" ]; then
        # echo "-a";
        all="1";
    elif [ "$i" = "-m" ]; then
        # echo "-m";
        msg="1";
    else    #msg
        if [ "`echo "$i" | egrep "^[^-]|^$"`" ]; then
            valid_msg="1";
        fi
    fi
done
# echo "$all"; echo "$msg"; echo "$valid_msg";

if [ $msg -eq "0" ] || [ $# -lt 2 ] || [ $valid_msg -eq "0" ]; then
    echo "usage: legit-commit [-a] -m commit-message"; exit 1;
fi

####  -a  ####
if [ $all -eq "1" ]; then
    # echo "--all";
    # NOT PROPERLY HANDLED DELETED FILES IN MAIN OR INDEX !!!!!
    # NOTE THIS COULD BE INEFFICIENT
    for i in "`sh legit-status | egrep -v "untracked|same as repo|delete" | cut -d'-' -f1`"
    do
        sh legit-add "$i";
    done
fi
# exit 0;
#############################################################################

index='.legit/index';
touch "$index/.status";
####  Stores all the file for status  ####
for i in `ls`
do
    if [ "`grep -o "^$i\$" "$index/.status"`" ]; then
        # already in .status don't add
        # echo "$i";
        continue;
    fi
    echo "$i" >> "$index/.status";  # useful for deleted files
done
# sort "$index/.status" > "$index/.status";
# exit 0;

##### whether to commit or not #####
# index='.legit/index';
if [ -f "$index/.index" ]; then
    commit_flag="0";
    for i in `ls $index`
    do
        # echo "HERE";
        if [ ! -f "$i" ]; then
            # means file has been rm
            continue;
            # echo "no hash";
            # exit 0;
        fi
        
        hash="`shasum $i | cut -d' ' -f1`";
        
        if [ "`grep $hash "$index/.index"`" ]; then
            # echo "$hash";
            continue;
        else
            commit_flag="1";
        fi
    done
else
    commit_flag="1";
    touch "$index/.index";
fi

# finally check for rm files
commit_num="0";
msg_file='.legit/COMMIT_EDITMSG';
if [ -s $msg_file ]; then            # Not Empty
     commit_num=`cut -d' ' -f1 $msg_file`;
     # commit_num=`expr $commit_num + 1`
fi
# echo $commit_num;

# index_sha="0";
#if [ -f "$index/.index" ]; then
index_sha=`shasum "$index/.index" | cut -d' ' -f1`;
# fi

repo='.legit/logs/repo';
snapshot="$repo/.snapshot.$commit_num";
# echo $snapshot;
if [ -d "$snapshot" ]; then
    snap_sha="`shasum "$snapshot/.index" | cut -d' ' -f1`";
    
fi
if [ "$snap_sha" != "$index_sha" ]; then
    commit_flag="1";
fi
# if [ ! -n "$snap_sha" ]; then
#    snap_sha="0";
# fi

# echo "$index_sha"; echo "$snap_sha"; exit 0;


if [ "$commit_flag" -eq 0 ]; then
    echo "nothing to commit"; exit 1;
fi

# echo "commiting for rm too!"; exit 0;
##### COMMIT_EDITMSG ##### (move above ^^^^)
commit_num="0";
# msg_file='.legit/COMMIT_EDITMSG';
if [ -s $msg_file ]; then            # Not Empty
     commit_num=`cut -d' ' -f1 $msg_file`;
     commit_num=`expr $commit_num + 1`
fi
echo "$commit_num $2" > $msg_file;  # number message

##### .snapshot.# #####
>"$index/.index"

snapshot="$repo/.snapshot.$commit_num";

mkdir $snapshot;    # .snapshot.#
touch "$snapshot/.index";

for i in `ls $index`
do
    cp "$index/$i" "$snapshot/$i";
    echo "`shasum $snapshot/$i`" >> "$index/.index";       # update hashes
    echo "`shasum $snapshot/$i`" >> "$snapshot/.index";       # update hashes
    
    # update status if file has been legit-rm or rm
    
done

# update status to match HEAD
for i in `cat "$index/.status"`
do
    main_sha="0";
    if [ -f "$i" ]; then
        main_sha=`shasum $i | cut -d' ' -f1`;
    fi

    index_sha="0";
    if [ -f "$index/$i" ]; then
        index_sha=`shasum "$index/$i" | cut -d' ' -f1`;
    fi
    
    if [ "$main_sha" = "0" ] && [ "$main_sha" = "$index_sha" ]; then
        # echo "HERE";
        sed -i "/^$i$/d" "$index/.status";
    fi
done

##### .logs/HEAD #####
log='.legit/logs/HEAD';
log_commit="commit: $commit_num $2";
echo "$log_commit" >> $log;     # commit: number message

echo "Committed as commit $commit_num";
