#!/bin/dash

if [ ! -d '.legit' ]; then
    echo "legit-status: error: no .legit directory containing legit repository exists";
    exit 1;
fi

if [ ! -d '.legit/logs/repo/.snapshot.0' ]; then
    echo "legit-status: error: your repository doesn't have any commits yet";
    exit 1;
fi

index='.legit/index';
commit_num="0";                      # Get latest repo #
msg_file='.legit/COMMIT_EDITMSG';

if [ -s $msg_file ]; then            # Not Empty
     commit_num=`cut -d' ' -f1 $msg_file`;
fi

repo='.legit/logs/repo';
snapshot="$repo/.snapshot.$commit_num";

for i in `cat "$index/.status"`
do
    main_sha="0";
    [ -f "$i" ] && main_sha=`sha1sum $i | cut -d' ' -f1`;

    index_sha="0";
    [ -f "$index/$i" ] && index_sha=`sha1sum "$index/$i" | cut -d' ' -f1`;

    snap_sha="`grep "$i$" "$snapshot/.index" | cut -d' ' -f1`";
    [ -z "$snap_sha" ] && snap_sha="0";

    # skip file is not in main, index or repo
    if [ "$main_sha" = "0" ] && [ "$index_sha" = "0" ] && [ "$snap_sha" = "0" ]; then
        continue;
    fi

    if   [ "$main_sha" != "0" ] && [ "$index_sha" != "0" ] && [ "$main_sha" != "$index_sha" ] && [ "$index_sha" != "$snap_sha" ]; then
        echo "$i - file changed, different changes staged for commit";
    elif [ "$main_sha" != "0" ] && [ "$main_sha" = "$index_sha" ] && [ "$index_sha" != "$snap_sha" ] && [ "$snap_sha" != "0" ]; then
        echo "$i - file changed, changes staged for commit";
    elif [ "$main_sha" != "0" ] && [ "$main_sha" != "$index_sha" ] && [ "$index_sha" = "$snap_sha" ] && [ "$snap_sha" != "0" ]; then
        echo "$i - file changed, changes not staged for commit";
    elif [ "$main_sha" = "0" ] && [ "$index_sha" = "$snap_sha" ]; then
        echo "$i - file deleted";
    elif [ "$main_sha" = "0" ] && [ "$main_sha" = "$index_sha" ] && [ "$snap_sha" != "0" ]; then
        echo "$i - deleted";
    elif [ "$main_sha" = "$index_sha" ] && [ "$index_sha" = "$snap_sha" ]; then
        echo "$i - same as repo";
    elif [ "$main_sha" = "$index_sha" ] && [ "$snap_sha" = "0" ]; then
        echo "$i - added to index";
    elif [ "$main_sha" != "0" ] && [ "$index_sha" = "0" ] && [ "$snap_sha" = "0" ]; then
        echo "$i - untracked";
    elif [ "$main_sha" != "0" ] && [ "$index_sha" = "0" ] && [ "$snap_sha" != "0" ]; then
        echo "$i - untracked";
    fi
done
