#!/bin/dash

# TODO
    # contain alpha-numeric characters plus '.', '-' and '_' characters.

if [ $# -eq 0 ]; then
    echo "usage: legit-add <filenames>";
    exit 1;
fi

if ! [ -d ".legit" ]; then
    echo "legit-add: error: no .legit directory containing legit repository exists";    
    exit 1;
fi

index='.legit/index';
for i in $@
do
    if [ ! -f "$i" ] && [ "`grep -o "^$i\$" "$index/.status"`" ]; then
        # file has been rmed so take out of .status and index
        if [ -f "$index/.status" ]; then
            sed -i "/\/$i$/d" "$index/.status"; # delete from status
        fi
        
        if [ -f "$index/.index" ]; then
            sed -i "/\/$i$/d" "$index/.index";  # delete from index
        fi

        if [ -f "$index/$i" ]; then
            rm "$index/$i";
        fi
        continue;
    fi

    if echo "$i" | egrep -qv "^[a-zA-Z0-9.-_]"; then
        continue;
    fi

    if [ -f "$i" ]; then
        if [ "`grep "\/*$i\$" "$index/.index"`" ]; then
            # update hash in .index
            index_sha="`grep "$i$" "$index/.index" | cut -d' ' -f1`";
            main_sha="`shasum "$i" | cut -d' ' -f1`";
            
            if [ "$main_sha" != "$index_sha" ]; then
                # LINUX
                sed -i "/$index_sha/d" "$index/.index";
                # MAC
                # sed -i -e "/$index_sha/d" "$index/.index";
                # rm "$index/.index-e";
                echo "`shasum $i`" >> "$index/.index";
            fi
        fi

        cp "$i" "$index/$i"
    else
        echo "legit-add: error: can not open '$i'";
        exit 1;
    fi
done
