#!/bin/bash

if [ $# -ne 0 ]; then
    echo "usage: legit-init"; exit 1;
fi

if [ -d ".legit" ]; then
    echo "legit-init: error: .legit already exists";    # not $0
    exit 1;
fi


mkdir ".legit";
touch ".legit/COMMIT_EDITMSG";         # latest commit msg stored here
mkdir ".legit/index";                  # staging file
mkdir ".legit/logs";
touch ".legit/logs/HEAD";              # git logs
mkdir ".legit/logs/repo";

# if works then add them
touch ".legit/index/.status";              # git logs
touch ".legit/index/.index";              # git logs

echo "Initialized empty legit repository in .legit";
