#!/bin/dash

        # TODO
        # convert to binary file
        # contain alpha-numeric characters plus '.', '-' and '_' characters.
        # legit-add again
        
        
if [ $# -eq 0 ]; then
    echo "usage: legit-add <filenames>"; 
    exit 0; 
fi

if ! [ -d ".legit" ]; then
    echo "legit-add: error: no .legit directory containing legit repository exists";    # not $0
    exit 0;
fi

for i in $@
do
    if echo "$i" | egrep -qv "^[a-zA-Z0-9]"; then
        continue;
    fi
    
    if test -f "$i"; then
        # premission | NOT COMPLETED
        permission=`stat -c %a "$i"`;

        # sha1 | NOT COMPLETED
        sha=`sha1sum "$i"`;

        # store
        echo "$permission $sha";
        echo "$permission $sha" > ".legit/.git/index";
    else
        echo "legit-add: error: can not open '$i'";
    fi
done

