#!/bin/dash

repo='.legit/logs/repo';
commit_num=`echo $1 | cut -d':' -f1`;
if [ -z "$commit_num" ]; then       # :file
      repo=".legit/index";
else
      repo="$repo/.snapshot.$commit_num";
fi

if [ ! -d "$repo" ]; then           # directory does not exist
    echo "legit-show: error: unknown commit '$commit_num'";
    exit 1;
fi

file=`echo $1 | cut -d':' -f2-`;
if [ ! -f "$repo/$file" ] && [ -z "$commit_num" ]; then
    echo "legit-show: error: '$file' not found in index";
elif [ ! -f "$repo/$file" ] && [ ! -z "$commit_num" ]; then
    echo "legit-show: error: '$file' not found in commit $commit_num";
else
    cat "$repo/$file";
fi
